# Generated by Django 2.1 on 2019-12-15 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 18, 27, 17, 14020, tzinfo=utc)),
        ),
    ]
