# Generated by Django 2.1.5 on 2019-12-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calc', '0003_auto_20191215_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
